/*
 * File: app/store/SalesHeaders.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.store.SalesHeaders', {
    extend: 'Ext.data.Store',

    requires: [
        'test.model.SalesHeader',
        'Ext.util.Grouper'
    ],

    config: {
        model: 'test.model.SalesHeader',
        storeId: 'SalesHeaders',
        sorters: {
            property: 'SalesOrderID'
        },
        grouper: {
            groupFn: function(item) {
                //return item.get('BusinessPartnerID');

                return item.get('BusinessPartnerID') + " - " + item.get('CustomerName');

            }
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {

        var tmpCustName="";
        var tmpCounter=0;
        var tmpAmount=0;

        aa = Ext.getStore('ChartStore');
        aa.removeAll();

        for (i=0; i<store.getCount(); i++){

            var custName = store.getAt(i).getData().CustomerName;

            if ( i===0){
                tmpCustName = custName;

            }
            if (custName === tmpCustName){
                tmpCounter =  tmpCounter + 1;
                tmpAmount = store.getAt(i).getData().TotalSum;
                var z = store.getCount()-1;
                if (i === z) {
                     //console.log (tmpCustName + "final >>>>" + tmpCounter);
                    aa.add({ name: tmpCustName, OrderCount: tmpCounter , OrderAmount: tmpAmount });
                }

           }
            else
            {
                //console.log (tmpCustName + ">>>>" + tmpCounter);
                aa.add({ name: tmpCustName, OrderCount: tmpCounter ,OrderAmount: tmpAmount});
                tmpCounter=1;
                tmpAmount = 0;
                tmpCustName=custName;
            }



        }
        aa.sync();

        //console.log("Chart Store updated, now Graph table has : " + aa.getCount() + " records");


    }

});