/*
 * File: app/view/BusinessPartner.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.BusinessPartner', {
    extend: 'Ext.form.Panel',
    alias: 'widget.businesspartner',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        itemId: 'myformpanel2',
        items: [
            {
                xtype: 'fieldset',
                disabled: false,
                itemId: 'myfieldset2',
                styleHtmlContent: true,
                instructions: 'Customer Details',
                title: 'Business Partner',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Company Name',
                        name: 'CompanyName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Customer',
                        name: 'BusinessPartnerID',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'E-Mail',
                        name: 'EmailAddress',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Phone',
                        name: 'PhoneNumber',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Fax',
                        name: 'FaxNumber',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Website',
                        name: 'WebAddress',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Street',
                        name: 'Street',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'City',
                        name: 'City',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'ZIP Code',
                        name: 'PostalCode',
                        readOnly: true
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyformpanelPainted',
                event: 'painted'
            }
        ]
    },

    onMyformpanelPainted: function(element, eOpts) {

        data = Ext.getStore('BusinessPartners');
        data1 = data.getAt(0);

        //var data = this;
        //console.log("Completed paint event for form");
        this.setValues(data1.getData());
        //http://stackoverflow.com/questions/17899171/how-to-pass-the-selected-item-to-the-next-view
    }

});