/*
 * File: app/view/SalesDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.SalesDetail', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.salesdetail',

    requires: [
        'test.view.SalesOrderView',
        'test.view.BusinessPartner',
        'test.view.SalesItemDetail',
        'test.view.SalesOrderItemList',
        'Ext.tab.Bar',
        'Ext.form.Panel',
        'Ext.dataview.List'
    ],

    config: {
        centered: false,
        height: '100%',
        itemId: 'mytabpanel',
        tabBar: {
            docked: 'bottom',
            layout: {
                type: 'hbox',
                align: 'center',
                pack: 'justify'
            }
        },
        items: [
            {
                xtype: 'salesorderview',
                iconCls: 'team'
            },
            {
                xtype: 'businesspartner',
                iconCls: 'user'
            },
            {
                xtype: 'salesitemdetail',
                hidden: true,
                iconCls: 'info'
            },
            {
                xtype: 'salesorderitemlist',
                iconCls: 'list'
            }
        ]
    }

});