/*
 * File: app/view/SalesItemDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.SalesItemDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.salesitemdetail',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        itemId: 'myformpanel1',
        items: [
            {
                xtype: 'fieldset',
                disabled: false,
                itemId: 'myfieldset2',
                styleHtmlContent: true,
                instructions: 'Line Item Details',
                title: 'Item Level',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Order ID',
                        name: 'SalesOrderID',
                        readOnly: false
                    },
                    {
                        xtype: 'textfield',
                        label: 'Line Item',
                        name: 'Position',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Material',
                        name: 'ProductName',
                        readOnly: false
                    },
                    {
                        xtype: 'textfield',
                        label: 'Material No',
                        name: 'ProductID',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Quantity',
                        name: 'Quantity',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Delivery Date',
                        name: 'DeliveryDate',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Net Amount',
                        name: 'NetSum',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Tax Amount',
                        name: 'Tax',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Total Amount',
                        name: 'TotalSum',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'showMat',
                        iconAlign: 'center',
                        iconCls: 'search',
                        text: 'Material'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyformpanelPainted',
                event: 'painted'
            },
            {
                fn: 'onMybutton7Tap',
                event: 'tap',
                delegate: '#showMat'
            }
        ]
    },

    onMyformpanelPainted: function(element, eOpts) {

        var data = this;
        //console.log("Completed paint event for form");
        this.setValues(data.getData());
        //http://stackoverflow.com/questions/17899171/how-to-pass-the-selected-item-to-the-next-view

        //debugger;

        //data.getData().ProductID

        //Load the Store MAterial Masters
        var matStore = Ext.getStore('MaterialMasters');
        var matUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/Products('" + data.getData().ProductID + "')";
        matStore.removeAll();
        matStore.getProxy().setPassword("YOURPASSWORD");
        matStore.getProxy().setUrl(matUrl);
        matStore.load(function (record, response,mainView) {
            //console.log("Request Status : " + response.success);
        });

    },

    onMybutton7Tap: function(button, e, eOpts) {

    }

});