/*
 * File: app/view/SalesOrderView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.SalesOrderView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.salesorderview',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Checkbox',
        'Ext.field.TextArea'
    ],

    config: {
        itemId: 'myformpanel',
        items: [
            {
                xtype: 'fieldset',
                disabled: false,
                itemId: 'myfieldset2',
                styleHtmlContent: true,
                instructions: 'Header',
                title: 'Sales Order',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Order ID',
                        name: 'SalesOrderID',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Customer Name',
                        name: 'CustomerName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Created',
                        name: 'CreatedAt',
                        readOnly: true
                    },
                    {
                        xtype: 'checkboxfield',
                        disabled: true,
                        label: 'Completed',
                        name: 'Status'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Description',
                        name: 'Note',
                        readOnly: true,
                        maxRows: 2
                    },
                    {
                        xtype: 'textfield',
                        label: 'Amount',
                        name: 'NetSum',
                        readOnly: true
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyformpanelPainted',
                event: 'painted'
            }
        ]
    },

    onMyformpanelPainted: function(element, eOpts) {
        //debugger;
        var data = this.up();
        //console.log("Completed paint event for form");
        this.setValues(data.getData());
        //http://stackoverflow.com/questions/17899171/how-to-pass-the-selected-item-to-the-next-view
    }

});