/*
 * File: app/view/SalesOrders.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.SalesOrders', {
    extend: 'Ext.dataview.List',
    alias: 'widget.salesorders',

    requires: [
        'Ext.XTemplate',
        'Ext.plugin.ListPaging',
        'Ext.plugin.PullRefresh'
    ],

    config: {
        itemId: 'mylist1',
        styleHtmlContent: true,
        emptyText: 'No records found',
        store: 'SalesHeaders',
        grouped: true,
        onItemDisclosure: true,
        masked: {
            xtype: 'loadmask',
            indicator: true,
            message: 'Loading...'
        },
        itemTpl: [
            '<div><b>Order: </b>{SalesOrderID}</div>',
            'Created: {CreatedAt}',
            ''
        ],
        plugins: [
            {
                ui: 'dark',
                autoPaging: true,
                type: 'listpaging'
            },
            {
                type: 'pullrefresh'
            }
        ]
    }

});