/*
 * File: app/view/SalesOrderItemList.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.SalesOrderItemList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.salesorderitemlist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'salesitemlist',
        styleHtmlContent: true,
        emptyText: 'No List Items found for Sales Order',
        store: 'SalesItems',
        grouped: true,
        pinHeaders: false,
        masked: {
            xtype: 'loadmask',
            indicator: true,
            message: 'Loading...'
        },
        itemTpl: [
            '{ProductName} - ${TotalSum}'
        ]
    }

});