/*
 * File: app/model/SalesHeader.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.model.SalesHeader', {
    extend: 'Ext.data.Model',
    alias: 'model.salesheader',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml'
    ],

    config: {
        fields: [
            {
                name: 'SalesOrderID'
            },
            {
                name: 'NetSum'
            },
            {
                name: 'Tax'
            },
            {
                name: 'Currency'
            },
            {
                name: 'ChangedAt'
            },
            {
                name: 'Note'
            },
            {
                convert: function(v, rec) {
                    return v.substring(0,10);

                },
                name: 'CreatedAt',
                type: 'date'
            },
            {
                name: 'TotalSum'
            },
            {
                convert: function(v, rec) {
                    if (v==="N"){
                        return false;
                    }else{
                        return true;
                    }
                },
                name: 'Status'
            },
            {
                name: 'CustomerName'
            },
            {
                name: 'BusinessPartnerID'
            }
        ],
        proxy: {
            type: 'ajax',
            limitParam: 'top',
            startParam: 'skip',
            url: 'http://uvo171cj1u5m9rqiv41.vm.cld.sr:8080/com.sales/SalesOrders',
            useDefaultXhrHeader: false,
            reader: {
                type: 'xml',
                record: 'entry'
            }
        }
    }
});