/*
 * File: app/model/SalesItem.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.model.SalesItem', {
    extend: 'Ext.data.Model',
    alias: 'model.salesitem',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest'
    ],

    config: {
        fields: [
            {
                name: 'QuantityUnit'
            },
            {
                name: 'Tax'
            },
            {
                name: 'NetSum'
            },
            {
                name: 'TotalSum'
            },
            {
                name: 'ProductName'
            },
            {
                name: 'ProductID'
            },
            {
                name: 'Position',
                type: 'int'
            },
            {
                name: 'SalesOrderID'
            },
            {
                name: 'Currency'
            },
            {
                name: 'Quantity'
            },
            {
                name: 'DeliveryDate'
            }
        ],
        proxy: {
            type: 'odata',
            enablePagingParams: false,
            url: 'https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/SalesOrders(\'0500000003\')/SalesOrderItems',
            password: 'YOURPASSWORD',
            useDefaultXhrHeader: false,
            username: 'P060866',
            withCredentials: true
        }
    }
});