/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.controller.Account', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'mainview',
            loginPanel: 'mainview #loginPanel',
            welcomePanel: 'mainview #welcomePanel',
            byBP: 'button#ByBP',
            showGraph: 'button#showGraph'
        },

        control: {
            "mainview #showLoginButton": {
                tap: 'showLogin'
            },
            "mainview #showRegisterButton": {
                tap: 'showRegister'
            },
            "loginform #loginButton": {
                tap: 'login'
            },
            "registerform #registerButton": {
                tap: 'register'
            },
            "button#ByBP": {
                tap: 'byBP'
            },
            "button#showGraph": {
                tap: 'showGraph'
            }
        }
    },

    showLogin: function(button, e, eOpts) {

        var loginForm = Ext.create('widget.loginform'),	// Login form
            mainView = this.getMainView();				// Main view

        // Navigate to login
        mainView.push({
            xtype: "loginform",
            title: "Choose the option"
        });

    },

    showRegister: function(button, e, eOpts) {

        var registerForm = Ext.create('widget.registerform'),	// Registration form
            mainView = this.getMainView();						// Main view

        // Navigate to register
        mainView.push({
            xtype: "registerform",
            title: "Register"
        });



    },

    login: function(button, e, eOpts) {
        /*
        var form = button.up('formpanel'),			// Login form
        	values = form.getValues(),				// Form values
        	mainView = this.getMainView(),			// Main view
        	loginPanel = this.getLoginPanel(),		// Login and register buttons
        	welcomePanel = this.getWelcomePanel();	// Welcome panel

        // Success
        var successCallback = function(resp, ops) {

            // Go back
            mainView.pop();

            // Hide login panel
            loginPanel.hide();

            // Show welcome panel
            welcomePanel.show();

        };

        // Failure
        var failureCallback = function(resp, ops) {

            // Show login failure error
            Ext.Msg.alert("Login Failure", resp);

        };


        // TODO: Login using server-side authentication service
        // Ext.Ajax.request({
        //		url: "/api/login",
        //		params: values,
        //		success: successCallback,
        //		failure: failureCallback
        // });

        // Just run success for now
        successCallback();
        */

        //Load the Store SalesOrders
        var byBPStore = Ext.getStore('SalesHeaders');
        var byBPUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/SalesOrders";
         byBPUrl = "http://uvo171cj1u5m9rqiv41.vm.cld.sr:8080/com.pavan.sales/SalesOrders"; //++PAVAN for SMP3.0

        byBPStore.removeAll();
        //byBPStore.getProxy().setPassword("PASSWORD");
        byBPStore.getProxy().setUrl(byBPUrl);
        byBPStore.load(function (record, response,mainView) {
            //console.log("Request Status : " + response.success);
        });

                var salesForm = Ext.create('widget.salesorders'),	// Login form
                    mainView = this.getMainView();				// Main view

                // Navigate to login
                mainView.push({
                    xtype: "salesorders",
                    title: "Sales Orders"
                });
    },

    register: function(button, e, eOpts) {

        var form = button.up('formpanel'),			// Login form
            values = form.getValues(),				// Form values
            mainView = this.getMainView(),			// Main view
            loginPanel = this.getLoginPanel(),		// Login and register buttons
            welcomePanel = this.getWelcomePanel();	// Welcome panel

        // Success
        var successCallback = function(resp, ops) {

            // Go back
            mainView.pop();

            // Hide login panel
            loginPanel.hide();

            // Show welcome panel
            welcomePanel.show();

        };

        // Failure
        var failureCallback = function(resp, ops) {

            // Show login failure error
            Ext.Msg.alert("Registration Failure", resp);

        };


        // TODO: Register using server-side authentication service
        // Ext.Ajax.request({
        //		url: "/api/register",
        //		params: values,
        //		success: successCallback,
        //		failure: failureCallback
        // });

        // Just run success for now
        successCallback();
    },

    byBP: function(button, e, eOpts) {
        //Load the Store BusinessPartner
        var businessStore = Ext.getStore('BusinessPartners');
        var businessUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/BusinessPartners";
        businessStore.removeAll();
        businessStore.getProxy().setPassword("YOURPASSWORD");
        businessStore.getProxy().setEnablePagingParams(true);
        businessStore.getProxy().setUseDefaultXhrHeader(true);
        businessStore.getProxy().setUrl(businessUrl);
        businessStore.load(function (record, response,mainView) {
            //console.log("Business Partner Request Status : " + response.success);
        });

        var salesForm = Ext.create('widget.bybusinesspartner'),	// Login form
            mainView = this.getMainView();				// Main view

        // Navigate to login
        mainView.push({
            xtype: "bybusinesspartner",
            title: "Customers"
        });

    },

    showGraph: function(button, e, eOpts) {

                //Load the Store SalesOrders
                var byBPStore = Ext.getStore('SalesHeaders');
        if (byBPStore.getCount() <=0){
           // alert("Loading store");
                var byBPUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/SalesOrders";
                byBPStore.removeAll();
                byBPStore.getProxy().setPassword("YOURPASSWORD");
                byBPStore.getProxy().setUrl(byBPUrl);
                byBPStore.load(function (record, response,mainView) {
                    //console.log("Request Status : " + response.success);

                });
        }
        else
        {
            //alert("Graph table exists >>" + byBPStore.getCount());
        }


        var registerForm = Ext.create('widget.mybarchart'),	// Registration form
            mainView = this.getMainView();						// Main view

        // Navigate to register
        mainView.push({
            xtype: "mybarchart",
            title: "Analytics"
        });
    }

});