/*
 * File: app/controller/SalesControl.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.controller.SalesControl', {
    extend: 'Ext.app.Controller',
    alias: 'controller.salescontrol',

    requires: [
        'test.view.SalesOrders'
    ],

    config: {
        refs: {
            salesOrders: 'list#mylist1',
            salesDetail: 'tabpanel#mytabpanel',
            mainView: 'navigationview#mynavigationview1',
            salesOrderView: 'formpanel#myformpanel',
            salesOrderItemList: 'list#salesitemlist',
            showMat: 'button#showMat',
            salesItemDetail: {
                autoCreate: true,
                selector: 'myformpanel1 #myfieldset2',
                xtype: 'salesitemdetail'
            },
            byBusinessPartner: 'list#byBPList'
        },

        control: {
            "salesOrders": {
                itemtap: 'onListItemTap'
            },
            "salesOrderItemList": {
                itemtap: 'onItemListTapped'
            },
            "showMat": {
                tap: 'showMat'
            },
            "byBusinessPartner": {
                itemtap: 'clickOnByBPList'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        //console.log(record.get('SalesOrderID'));


        //Load the Store SalesOrders

        var cListStore = Ext.getStore('SalesOrders');
        var tmpUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/SalesOrders('" + record.get('SalesOrderID') + "')";
        cListStore.removeAll();
        cListStore.getProxy().setPassword("YOURPASSWORD");
        cListStore.getProxy().setUrl(tmpUrl);
        cListStore.load(function (record, response,mainView) {
            //console.log("Request Status : " + response.success);

        });

        //Load the Store SalesOrders

        var itemStore = Ext.getStore('SalesItems');
        var itemUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/SalesOrders('" + record.get('SalesOrderID') + "')/SalesOrderItems";

        itemStore.removeAll();
        itemStore.getProxy().setPassword("YOURPASSWORD");
        itemStore.getProxy().setUrl(itemUrl);
        itemStore.load(function (record, response,mainView) {
            //console.log("Item Request Status : " + response.success);

        });

        //Load the Store BusinessPartner
        var businessStore = Ext.getStore('BusinessPartners');
        var businessUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/BusinessPartners('" + record.get('BusinessPartnerID') + "')";
        businessStore.removeAll();
        businessStore.getProxy().setPassword("YOURPASSWORD");
        businessStore.getProxy().setEnablePagingParams(false);
        businessStore.getProxy().setUseDefaultXhrHeader(false);
        businessStore.getProxy().setUrl(businessUrl);
        businessStore.load(function (record, response,mainView) {
            //console.log("Business Partner Request Status : " + response.success);
        });


        //Load next page
        var loginForm = Ext.create('widget.salesdetail'),	// Login form
            mainView = this.getMainView();				// Main view

        mainView.push({
            xtype: "salesdetail",
            title: "Details",
            data: record.getData()
        });





        /*

        //Load next page
        var loginForm = Ext.create('widget.salesorderview'),	// Login form
            mainView = this.getMainView();				// Main view
        mainView.push({
            xtype: "salesorderview",
            title: "Details",
            data: record.getData()
        });
        */
    },

    onItemListTapped: function(dataview, index, target, record, e, eOpts) {
                //Load next page
                var loginForm = Ext.create('widget.salesitemdetail'),	// Login form
                    mainView = this.getMainView();				// Main view

                mainView.push({
                    xtype: "salesitemdetail",
                    title: "Item Details",
                    data: record.getData()
                });
    },

    showMat: function(button, e, eOpts) {
        /*
        var matID = button.up('salesitemdetail').getValues().ProductID;


        //this.getFields('ProductID').getValue()

        //Load the Store MAterial Masters
        var matStore = Ext.getStore('MaterialMasters');
        var matUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/Products('" + matID + "')";
        matStore.removeAll();
        matStore.getProxy().setPassword("YOURPASSWORD");
        matStore.getProxy().setUrl(matUrl);
        matStore.load(function (record, response,mainView) {
            console.log("Request Status : " + response.success);
        });
        */

                //Load next page
                var loginForm = Ext.create('widget.materialmaster'),	// Login form
                    mainView = this.getMainView();				// Main view

                mainView.push({
                    xtype: "materialmaster",
                    title: "Material Master"
                    //data: matStore.getData()
                });

    },

    clickOnByBPList: function(dataview, index, target, record, e, eOpts) {
        //Load the Store SalesOrders
        var byBPStore = Ext.getStore('SalesHeaders');
        var byBPUrl = "https://sapes1.sapdevcenter.com/sap/opu/odata/sap/ZCD204_EPM_DEMO_SRV/BusinessPartners('" + record.get('BusinessPartnerID') + "')/SalesOrders";
        byBPStore.removeAll();
        byBPStore.getProxy().setPassword("YOURPASSWORD");
        byBPStore.getProxy().setUrl(byBPUrl);
        byBPStore.load(function (record, response,mainView) {
            //console.log("Request Status : " + response.success);

        });

        var salesForm = Ext.create('widget.salesorders'),	// Login form
            mainView = this.getMainView();				// Main view

        // Navigate to login
        mainView.push({
            xtype: "salesorders",
            title: "Sales Orders"
        });
    }

});